### ISSUE TITLE
Not sure if I broke something getting error

### ISSUE THREAD

**Issue by yarafie** [freearhey/epg-grabber#4]
I recently updated epg-grabber and it seems something  broke?

getting the below error when running it.

grabbing the guide...

Starting...
Loading './sites.test/elcinema.com.test.config.js'...
Parsing:
Loading 'sites.test/elcinema.com.test.channels.xml'...
/data/data/com.termux/files/usr/lib/node_modules/epg-grabber/src/utils.js:54
  return channels.elements
                  ^

TypeError: Cannot read properties of undefined (reading 'elements')
    at Object.utils.parseChannels (/data/data/com.termux/files/usr/lib/node_modules/epg-grabber/src/utils.js:54:19)
    at main (/data/data/com.termux/files/usr/lib/node_modules/epg-grabber/bin/epg-grabber.js:40:26)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/epg-grabber/bin/epg-grabber.js:66:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

attached the two files gzipped

>
[elcinema.com.test.channels.xml.gz](https://github.com/freearhey/epg-grabber/files/7319719/elcinema.com.test.channels.xml.gz)
[elcinema.com.test.config.js.gz](https://github.com/freearhey/epg-grabber/files/7319721/elcinema.com.test.config.js.gz)

**Comment by yarafie** [comment]
v0.10.0 Master has a problem reverted back to 0 9.1 works fine
